In [ ]:
# Assignment 4: Basic Statistics - 2
## Hospital Patient Data Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
patient_df = pd.read_csv("Patient_Data.csv")
billing_df = pd.read_csv("Billing_Data.csv")

In [3]:
patient_df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [4]:
billing_df.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

# Task-1

In [5]:
patient_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      str
 2   Department      6 non-null      str
 3   Doctor          6 non-null      str
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      str
dtypes: float64(1), int64(2), str(4)
memory usage: 468.0 bytes

In [6]:
billing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

# Task-2

In [7]:
billing_columns = patient_df[['PatientID', 'Department', 'Doctor', 'BillAmount']]
billing_columns

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

# Task-3

In [8]:
patient_df = patient_df.drop(columns=['ReceptionistID', 'CheckInTime'])
patient_df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

# Task-4

In [9]:
patient_df.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

# Task-5

In [10]:
patient_df = patient_df.drop_duplicates(subset='PatientID')

# Task-6

In [11]:
patient_df['BillAmount'] = patient_df['BillAmount'].fillna(patient_df['BillAmount'].mean())
patient_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333


# Task-7

In [12]:
merged_df = pd.merge(patient_df, billing_df, on='PatientID')
merged_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

# Task-8

In [13]:
new_patient = pd.DataFrame({
    'PatientID':[106],
    'Name':['John'],
    'Department':['Orthopedics'],
    'Doctor':['Dr. Alex'],
    'BillAmount':[6500]
})

patient_df = pd.concat([patient_df, new_patient], ignore_index=True)
patient_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106     John  Orthopedics   Dr. Alex  6500.000000

# Task-9

In [14]:
new_columns = billing_df[['InsuranceCovered','FinalAmount']]

final_df = pd.concat([patient_df, new_columns], axis=1)
final_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0
5,106,John,Orthopedics,Dr. Alex,6500.000000,NaN,NaN

## Conclusion

- Loaded and analyzed the patient and billing datasets.
- Selected required columns and removed unnecessary columns.
- Calculated department-wise bill amounts using GroupBy.
- Removed duplicate patient records.
- Filled missing bill amounts with the mean.
- Merged patient and billing datasets.
- Added new patient records using concatenation.
- Added billing columns using column-wise concatenation.
- Successfully prepared the dataset for further analysis.