In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

In [4]:
df = pd.read_csv("adult_with_headers (1).csv")
df.head()

   age          workclass  fnlwgt  ... hours_per_week  native_country  income
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K
4   28            Private  338409  ...             40            Cuba   <=50K

[5 rows x 15 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [9]:
df.describe()

                age        fnlwgt  ...  capital_loss  hours_per_week
count  32561.000000  3.256100e+04  ...  32561.000000    32561.000000
mean      38.581647  1.897784e+05  ...     87.303830       40.437456
std       13.640433  1.055500e+05  ...    402.960219       12.347429
min       17.000000  1.228500e+04  ...      0.000000        1.000000
25%       28.000000  1.178270e+05  ...      0.000000       40.000000
50%       37.000000  1.783560e+05  ...      0.000000       40.000000
75%       48.000000  2.370510e+05  ...      0.000000       45.000000
max       90.000000  1.484705e+06  ...   4356.000000       99.000000

[8 rows x 6 columns]

In [10]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [11]:
(df == "?").sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(24)

In [14]:
print("Rows and Columns:", df.shape)

Rows and Columns: (32561, 15)

In [15]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [16]:
(df == "?").sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [17]:
for col in df.columns:
  print(col, (df[col] == "?").sum())

age 0
workclass 0
fnlwgt 0
education 0
education_num 0
marital_status 0
occupation 0
relationship 0
race 0
sex 0
capital_gain 0
capital_loss 0
hours_per_week 0
native_country 0
income 0

In [18]:
import numpy as np
df.replace("?", np.nan, inplace=True)

In [19]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [20]:
from sklearn.preprocessing import StandardScaler

numerical_cols = ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

scaler = StandardScaler()

df_standard = df.copy()
df_standard[numerical_cols] = scaler.fit_transform(df_standard[numerical_cols])

df_standard.head()

        age          workclass  ...  native_country  income
0  0.030671          State-gov  ...   United-States   <=50K
1  0.837109   Self-emp-not-inc  ...   United-States   <=50K
2 -0.042642            Private  ...   United-States   <=50K
3  1.057047            Private  ...   United-States   <=50K
4 -0.775768            Private  ...            Cuba   <=50K

[5 rows x 15 columns]

In [21]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

df_minmax = df.copy()
df_minmax[numerical_cols] = minmax.fit_transform(df_minmax[numerical_cols])

df_minmax.head()

        age          workclass  ...  native_country  income
0  0.301370          State-gov  ...   United-States   <=50K
1  0.452055   Self-emp-not-inc  ...   United-States   <=50K
2  0.287671            Private  ...   United-States   <=50K
3  0.493151            Private  ...   United-States   <=50K
4  0.150685            Private  ...            Cuba   <=50K

[5 rows x 15 columns]

Explain the difference

Standard Scaling: Transforms data to have a mean of 0 and a standard deviation of 1. It is preferred for algorithms such as Logistic Regression, SVM, and PCA.

Min-Max Scaling: Scales values to the range 0–1. It is useful for Neural Networks and distance-based algorithms like KNN.

In [22]:
# Find categorical columns with less than 5 unique values
small_cat_cols = [col for col in df.select_dtypes(include='object').columns
                  if df[col].nunique() < 5]

print(small_cat_cols)

df_onehot = pd.get_dummies(df, columns=small_cat_cols)

df_onehot.head()

['sex', 'income']

   age          workclass  fnlwgt  ... sex_ Male  income_ <=50K income_ >50K
0   39          State-gov   77516  ...      True           True        False
1   50   Self-emp-not-inc   83311  ...      True           True        False
2   38            Private  215646  ...      True           True        False
3   53            Private  234721  ...      True           True        False
4   28            Private  338409  ...     False           True        False

[5 rows x 17 columns]

In [23]:
from sklearn.preprocessing import LabelEncoder

df_label = df.copy()

le = LabelEncoder()

for col in df_label.select_dtypes(include='object').columns:
    df_label[col] = le.fit_transform(df_label[col])

df_label.head()

   age  workclass  fnlwgt  ...  hours_per_week  native_country  income
0   39          7   77516  ...              40              39       0
1   50          6   83311  ...              13              39       0
2   38          4  215646  ...              40              39       0
3   53          4  234721  ...              40              39       0
4   28          4  338409  ...              40               5       0

[5 rows x 15 columns]

One-Hot Encoding:
• Creates a new binary column for each category.
• Best for columns with fewer categories.

Label Encoding:
• Assigns a numeric value to each category.
• Best for columns with many categories.

In [25]:
df['capital_total'] = df['capital_gain'] - df['capital_loss']

df['age_per_education'] = df['age'] / df['education_num']

df.head()

   age          workclass  fnlwgt  ...  income  capital_total age_per_education
0   39          State-gov   77516  ...   <=50K           2174          3.000000
1   50   Self-emp-not-inc   83311  ...   <=50K              0          3.846154
2   38            Private  215646  ...   <=50K              0          4.222222
3   53            Private  234721  ...   <=50K              0          7.571429
4   28            Private  338409  ...   <=50K              0          2.153846

[5 rows x 17 columns]

Feature 1: capital_total

Combines capital gain and capital loss into one feature to represent the overall capital amount.

Feature 2: age_per_education

Represents the relationship between a person’s age and education level, which may help improve prediction.

In [26]:
import numpy as np

df['fnlwgt_log'] = np.log1p(df['fnlwgt'])

df[['fnlwgt', 'fnlwgt_log']].head()

   fnlwgt  fnlwgt_log
0   77516   11.258253
1   83311   11.330348
2  215646   12.281398
3  234721   12.366157
4  338409   12.732013

Log Transformation

Log transformation reduces skewness in numerical data and makes the distribution more normal, which can improve machine learning model performance.