In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [11]:
df = pd.read_csv("sonardataset.csv")

In [12]:
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  Y       208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [14]:
df.isnull().sum()

x_1     0
x_2     0
x_3     0
x_4     0
x_5     0
       ..
x_57    0
x_58    0
x_59    0
x_60    0
Y       0
Length: 61, dtype: int64

In [16]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [17]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

print(y[:10])

[1 1 1 1 1 1 1 1 1 1]

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(166, 60)
(42, 60)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

# Hidden Layer
model.add(Dense(32, input_dim=60, activation='relu'))

# Output Layer
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │         1,952 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,985 (7.75 KB)

 Trainable params: 1,985 (7.75 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [22]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=10,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.5606 - loss: 0.6841 - val_accuracy: 0.5882 - val_loss: 0.7007
Epoch 2/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6591 - loss: 0.5720 - val_accuracy: 0.5882 - val_loss: 0.6489
Epoch 3/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7348 - loss: 0.5057 - val_accuracy: 0.7059 - val_loss: 0.6141
Epoch 4/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7803 - loss: 0.4561 - val_accuracy: 0.7353 - val_loss: 0.5807
Epoch 5/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8182 - loss: 0.4131 - val_accuracy: 0.7647 - val_loss: 0.5534
Epoch 6/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8485 - loss: 0.3805 - val_accuracy: 0.7647 - val_loss: 0.5396
Epoch 7/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8636 - loss: 0.3542 - val_accuracy: 0.7647 - val_loss: 0.5271
Epoch 8/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8864 - loss: 0.3320 - val_accuracy: 0.7647 - val_loss: 0.5110
Epoch 9/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8939 - loss: 0.3092 - val_accuracy: 0.7647 - val_loss: 0.4882
Epoch 10/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9091 - loss: 0.2904 - val_accuracy: 0.7647 - val_loss: 0.4788
Epoch 11/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9091 - loss: 0.2727 - val_accuracy: 0.7647 - val_loss: 0.4693
Epoch 12/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9318 - loss: 0.2555 - val_accuracy: 0.7647 - val_loss: 0.4594
Epoch 13/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9318 - loss: 0.2414 - val_accuracy: 0.7647 - val_loss: 0.4494
Epoch 14/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9394 - loss: 0.2280 - val_accuracy: 0.7941 - val_loss: 0.4359
Epoch 15/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9470 - loss: 0.2153 - val_accuracy: 0.7941 - val_loss: 0.4325
Epoch 16/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.2016 - val_accuracy: 0.8235 - val_loss: 0.4122
Epoch 17/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1913 - val_accuracy: 0.7941 - val_loss: 0.4098
Epoch 18/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1805 - val_accuracy: 0.7941 - val_loss: 0.4086
Epoch 19/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1720 - val_accuracy: 0.8235 - val_loss: 0.4019
Epoch 20/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1627 - val_accuracy: 0.8235 - val_loss: 0.4003
Epoch 21/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.1553 - val_accuracy: 0.8235 - val_loss: 0.4066
Epoch 22/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9773 - loss: 0.1473 - val_accuracy: 0.8529 - val_loss: 0.3991
Epoch 23/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.1401 - val_accuracy: 0.8529 - val_loss: 0.3936
Epoch 24/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9848 - loss: 0.1336 - val_accuracy: 0.8529 - val_loss: 0.3923
Epoch 25/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9924 - loss: 0.1271 - val_accuracy: 0.8529 - val_loss: 0.3941
Epoch 26/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1218 - val_accuracy: 0.8529 - val_loss: 0.3952
Epoch 27/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1157 - val_accuracy: 0.8529 - val_loss: 0.3906
Epoch 28/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1112 - val_accuracy: 0.8529 - val_loss: 0.3883
Epoch 29/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1071 - val_accuracy: 0.8235 - val_loss: 0.4050
Epoch 30/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1023 - val_accuracy: 0.8529 - val_loss: 0.3933
Epoch 31/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9924 - loss: 0.0974 - val_accuracy: 0.8529 - val_loss: 0.4038
Epoch 32/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0926 - val_accuracy: 0.8529 - val_loss: 0.3985
Epoch 33/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0888 - val_accuracy: 0.8529 - val_loss: 0.3964
Epoch 34/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0849 - val_accuracy: 0.8529 - val_loss: 0.3934
Epoch 35/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0810 - val_accuracy: 0.8529 - val_loss: 0.3945
Epoch 36/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0779 - val_accuracy: 0.8529 - val_loss: 0.3917
Epoch 37/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0749 - val_accuracy: 0.8529 - val_loss: 0.3977
Epoch 38/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0718 - val_accuracy: 0.8529 - val_loss: 0.3941
Epoch 39/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0687 - val_accuracy: 0.8529 - val_loss: 0.3948
Epoch 40/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0670 - val_accuracy: 0.8824 - val_loss: 0.3754
Epoch 41/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0639 - val_accuracy: 0.8824 - val_loss: 0.3810
Epoch 42/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0611 - val_accuracy: 0.8824 - val_loss: 0.3882
Epoch 43/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0589 - val_accuracy: 0.8529 - val_loss: 0.3950
Epoch 44/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0564 - val_accuracy: 0.8529 - val_loss: 0.3959
Epoch 45/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0543 - val_accuracy: 0.8529 - val_loss: 0.3953
Epoch 46/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0520 - val_accuracy: 0.8529 - val_loss: 0.4013
Epoch 47/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0506 - val_accuracy: 0.8235 - val_loss: 0.4062
Epoch 48/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0484 - val_accuracy: 0.8529 - val_loss: 0.4016
Epoch 49/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0466 - val_accuracy: 0.8824 - val_loss: 0.3981
Epoch 50/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0448 - val_accuracy: 0.8824 - val_loss: 0.4023
Epoch 51/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0431 - val_accuracy: 0.8529 - val_loss: 0.4127
Epoch 52/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0418 - val_accuracy: 0.8529 - val_loss: 0.4128
Epoch 53/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0410 - val_accuracy: 0.8824 - val_loss: 0.3900
Epoch 54/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0393 - val_accuracy: 0.8529 - val_loss: 0.3974
Epoch 55/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0376 - val_accuracy: 0.8529 - val_loss: 0.4060
Epoch 56/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0363 - val_accuracy: 0.8529 - val_loss: 0.4146
Epoch 57/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0348 - val_accuracy: 0.8529 - val_loss: 0.4145
Epoch 58/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0338 - val_accuracy: 0.8529 - val_loss: 0.4159
Epoch 59/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0326 - val_accuracy: 0.8529 - val_loss: 0.4225
Epoch 60/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0316 - val_accuracy: 0.8529 - val_loss: 0.4249
Epoch 61/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0307 - val_accuracy: 0.8529 - val_loss: 0.4284
Epoch 62/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0297 - val_accuracy: 0.8529 - val_loss: 0.4250
Epoch 63/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0288 - val_accuracy: 0.8529 - val_loss: 0.4248
Epoch 64/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0280 - val_accuracy: 0.8529 - val_loss: 0.4303
Epoch 65/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0270 - val_accuracy: 0.8529 - val_loss: 0.4386
Epoch 66/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0261 - val_accuracy: 0.8529 - val_loss: 0.4366
Epoch 67/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0254 - val_accuracy: 0.8529 - val_loss: 0.4403
Epoch 68/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0247 - val_accuracy: 0.8529 - val_loss: 0.4437
Epoch 69/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0240 - val_accuracy: 0.8529 - val_loss: 0.4422
Epoch 70/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0231 - val_accuracy: 0.8235 - val_loss: 0.4481
Epoch 71/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0224 - val_accuracy: 0.8235 - val_loss: 0.4515
Epoch 72/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0217 - val_accuracy: 0.8235 - val_loss: 0.4537
Epoch 73/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0211 - val_accuracy: 0.8529 - val_loss: 0.4524
Epoch 74/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0205 - val_accuracy: 0.8235 - val_loss: 0.4647
Epoch 75/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0198 - val_accuracy: 0.8235 - val_loss: 0.4603
Epoch 76/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0193 - val_accuracy: 0.8529 - val_loss: 0.4570
Epoch 77/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0187 - val_accuracy: 0.8529 - val_loss: 0.4580
Epoch 78/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0183 - val_accuracy: 0.8529 - val_loss: 0.4615
Epoch 79/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0178 - val_accuracy: 0.8235 - val_loss: 0.4637
Epoch 80/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0174 - val_accuracy: 0.8235 - val_loss: 0.4674
Epoch 81/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0169 - val_accuracy: 0.8235 - val_loss: 0.4688
Epoch 82/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0164 - val_accuracy: 0.8235 - val_loss: 0.4689
Epoch 83/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0160 - val_accuracy: 0.8235 - val_loss: 0.4707
Epoch 84/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0156 - val_accuracy: 0.8235 - val_loss: 0.4752
Epoch 85/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0153 - val_accuracy: 0.8235 - val_loss: 0.4772
Epoch 86/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0149 - val_accuracy: 0.7941 - val_loss: 0.4807
Epoch 87/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0146 - val_accuracy: 0.8235 - val_loss: 0.4789
Epoch 88/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0142 - val_accuracy: 0.7941 - val_loss: 0.4854
Epoch 89/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0139 - val_accuracy: 0.7941 - val_loss: 0.4869
Epoch 90/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0135 - val_accuracy: 0.7941 - val_loss: 0.4876
Epoch 91/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0133 - val_accuracy: 0.7941 - val_loss: 0.4973
Epoch 92/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0129 - val_accuracy: 0.7941 - val_loss: 0.4962
Epoch 93/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0126 - val_accuracy: 0.7941 - val_loss: 0.4934
Epoch 94/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0123 - val_accuracy: 0.7941 - val_loss: 0.4931
Epoch 95/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0120 - val_accuracy: 0.7941 - val_loss: 0.4947
Epoch 96/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0118 - val_accuracy: 0.8235 - val_loss: 0.4853
Epoch 97/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0115 - val_accuracy: 0.8235 - val_loss: 0.4833
Epoch 98/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0112 - val_accuracy: 0.8235 - val_loss: 0.4858
Epoch 99/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0110 - val_accuracy: 0.7941 - val_loss: 0.4913
Epoch 100/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0108 - val_accuracy: 0.7941 - val_loss: 0.4969

In [23]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8571 - loss: 0.3536
Test Loss: 0.35361117124557495
Test Accuracy: 0.8571428656578064

In [24]:
y_pred = model.predict(X_test)

# Convert probabilities to 0 or 1
y_pred = (y_pred > 0.5).astype(int)

print(y_pred[:10])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]]

In [26]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[20  6]
 [ 0 16]]

In [27]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.77      0.87        26
           1       0.73      1.00      0.84        16

    accuracy                           0.86        42
   macro avg       0.86      0.88      0.86        42
weighted avg       0.90      0.86      0.86        42

In [28]:
model2 = Sequential()

model2.add(Dense(64, input_dim=60, activation='relu'))
model2.add(Dense(32, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))

model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history2 = model2.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=10,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.5682 - loss: 0.7605 - val_accuracy: 0.5882 - val_loss: 0.7028
Epoch 2/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7424 - loss: 0.5508 - val_accuracy: 0.6471 - val_loss: 0.6099
Epoch 3/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8409 - loss: 0.4491 - val_accuracy: 0.6765 - val_loss: 0.5627
Epoch 4/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8788 - loss: 0.3780 - val_accuracy: 0.6765 - val_loss: 0.5236
Epoch 5/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8939 - loss: 0.3239 - val_accuracy: 0.7353 - val_loss: 0.4943
Epoch 6/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9318 - loss: 0.2777 - val_accuracy: 0.7941 - val_loss: 0.4657
Epoch 7/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9545 - loss: 0.2412 - val_accuracy: 0.7647 - val_loss: 0.4484
Epoch 8/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.2088 - val_accuracy: 0.7941 - val_loss: 0.4243
Epoch 9/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1803 - val_accuracy: 0.7941 - val_loss: 0.4294
Epoch 10/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9697 - loss: 0.1575 - val_accuracy: 0.7647 - val_loss: 0.4228
Epoch 11/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1365 - val_accuracy: 0.7941 - val_loss: 0.4115
Epoch 12/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.1212 - val_accuracy: 0.7353 - val_loss: 0.4371
Epoch 13/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.1012 - val_accuracy: 0.7647 - val_loss: 0.4324
Epoch 14/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9924 - loss: 0.0906 - val_accuracy: 0.7941 - val_loss: 0.4289
Epoch 15/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0753 - val_accuracy: 0.7059 - val_loss: 0.4867
Epoch 16/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0674 - val_accuracy: 0.7059 - val_loss: 0.4780
Epoch 17/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0578 - val_accuracy: 0.7353 - val_loss: 0.4594
Epoch 18/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0505 - val_accuracy: 0.7353 - val_loss: 0.4760
Epoch 19/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0448 - val_accuracy: 0.7647 - val_loss: 0.4684
Epoch 20/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0388 - val_accuracy: 0.7353 - val_loss: 0.4974
Epoch 21/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0332 - val_accuracy: 0.7647 - val_loss: 0.4934
Epoch 22/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0295 - val_accuracy: 0.7647 - val_loss: 0.5053
Epoch 23/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0262 - val_accuracy: 0.7647 - val_loss: 0.4827
Epoch 24/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0235 - val_accuracy: 0.7647 - val_loss: 0.5080
Epoch 25/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0209 - val_accuracy: 0.7647 - val_loss: 0.5357
Epoch 26/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0185 - val_accuracy: 0.7647 - val_loss: 0.5405
Epoch 27/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0165 - val_accuracy: 0.7647 - val_loss: 0.5489
Epoch 28/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0150 - val_accuracy: 0.7647 - val_loss: 0.5705
Epoch 29/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0136 - val_accuracy: 0.7647 - val_loss: 0.5736
Epoch 30/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0122 - val_accuracy: 0.7647 - val_loss: 0.5883
Epoch 31/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0111 - val_accuracy: 0.7647 - val_loss: 0.6010
Epoch 32/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0102 - val_accuracy: 0.7647 - val_loss: 0.6023
Epoch 33/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0094 - val_accuracy: 0.7647 - val_loss: 0.6109
Epoch 34/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0085 - val_accuracy: 0.7647 - val_loss: 0.6125
Epoch 35/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0079 - val_accuracy: 0.7647 - val_loss: 0.6263
Epoch 36/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0072 - val_accuracy: 0.7647 - val_loss: 0.6372
Epoch 37/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.7353 - val_loss: 0.6424
Epoch 38/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0062 - val_accuracy: 0.7647 - val_loss: 0.6504
Epoch 39/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0058 - val_accuracy: 0.7647 - val_loss: 0.6572
Epoch 40/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0054 - val_accuracy: 0.7353 - val_loss: 0.6735
Epoch 41/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0051 - val_accuracy: 0.7647 - val_loss: 0.6821
Epoch 42/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0047 - val_accuracy: 0.7647 - val_loss: 0.6712
Epoch 43/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0044 - val_accuracy: 0.7647 - val_loss: 0.6752
Epoch 44/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0041 - val_accuracy: 0.7647 - val_loss: 0.6854
Epoch 45/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0039 - val_accuracy: 0.7647 - val_loss: 0.6865
Epoch 46/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.7647 - val_loss: 0.6937
Epoch 47/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0035 - val_accuracy: 0.7647 - val_loss: 0.6987
Epoch 48/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.7647 - val_loss: 0.7104
Epoch 49/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0031 - val_accuracy: 0.7647 - val_loss: 0.7154
Epoch 50/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.7647 - val_loss: 0.7191
Epoch 51/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.7647 - val_loss: 0.7199
Epoch 52/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.7647 - val_loss: 0.7263
Epoch 53/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.7647 - val_loss: 0.7371
Epoch 54/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.7647 - val_loss: 0.7386
Epoch 55/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0024 - val_accuracy: 0.7647 - val_loss: 0.7434
Epoch 56/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.7647 - val_loss: 0.7446
Epoch 57/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.7647 - val_loss: 0.7497
Epoch 58/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.7647 - val_loss: 0.7571
Epoch 59/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.7647 - val_loss: 0.7614
Epoch 60/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.7647 - val_loss: 0.7676
Epoch 61/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.7647 - val_loss: 0.7674
Epoch 62/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.7647 - val_loss: 0.7779
Epoch 63/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7647 - val_loss: 0.7740
Epoch 64/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.7647 - val_loss: 0.7869
Epoch 65/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.7647 - val_loss: 0.8001
Epoch 66/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7647 - val_loss: 0.7968
Epoch 67/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.7647 - val_loss: 0.7953
Epoch 68/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.7647 - val_loss: 0.8021
Epoch 69/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.7647 - val_loss: 0.8054
Epoch 70/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.7647 - val_loss: 0.8159
Epoch 71/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7647 - val_loss: 0.7985
Epoch 72/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7647 - val_loss: 0.7915
Epoch 73/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7647 - val_loss: 0.7993
Epoch 74/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.7647 - val_loss: 0.8116
Epoch 75/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.7647 - val_loss: 0.8174
Epoch 76/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.7647 - val_loss: 0.8240
Epoch 77/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.7647 - val_loss: 0.8300
Epoch 78/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 9.7785e-04 - val_accuracy: 0.7647 - val_loss: 0.8193
Epoch 79/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.5008e-04 - val_accuracy: 0.7647 - val_loss: 0.8229
Epoch 80/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.1724e-04 - val_accuracy: 0.7647 - val_loss: 0.8349
Epoch 81/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 8.8778e-04 - val_accuracy: 0.7647 - val_loss: 0.8285
Epoch 82/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.5942e-04 - val_accuracy: 0.7647 - val_loss: 0.8287
Epoch 83/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.3146e-04 - val_accuracy: 0.7647 - val_loss: 0.8352
Epoch 84/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.0633e-04 - val_accuracy: 0.7647 - val_loss: 0.8458
Epoch 85/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.8144e-04 - val_accuracy: 0.7647 - val_loss: 0.8512
Epoch 86/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.5991e-04 - val_accuracy: 0.7647 - val_loss: 0.8532
Epoch 87/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.3931e-04 - val_accuracy: 0.7647 - val_loss: 0.8513
Epoch 88/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.1853e-04 - val_accuracy: 0.7647 - val_loss: 0.8561
Epoch 89/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 6.9877e-04 - val_accuracy: 0.7647 - val_loss: 0.8602
Epoch 90/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.7972e-04 - val_accuracy: 0.7647 - val_loss: 0.8619
Epoch 91/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.6194e-04 - val_accuracy: 0.7647 - val_loss: 0.8655
Epoch 92/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.4424e-04 - val_accuracy: 0.7647 - val_loss: 0.8679
Epoch 93/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.3007e-04 - val_accuracy: 0.7647 - val_loss: 0.8775
Epoch 94/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.1080e-04 - val_accuracy: 0.7647 - val_loss: 0.8781
Epoch 95/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.9660e-04 - val_accuracy: 0.7647 - val_loss: 0.8801
Epoch 96/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.8060e-04 - val_accuracy: 0.7647 - val_loss: 0.8870
Epoch 97/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.6609e-04 - val_accuracy: 0.7647 - val_loss: 0.8917
Epoch 98/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.5120e-04 - val_accuracy: 0.7647 - val_loss: 0.8936
Epoch 99/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.3863e-04 - val_accuracy: 0.7647 - val_loss: 0.8920
Epoch 100/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 5.2555e-04 - val_accuracy: 0.7647 - val_loss: 0.8972

In [29]:
loss2, accuracy2 = model2.evaluate(X_test, y_test)

print("Tuned Model Accuracy:", accuracy2)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8810 - loss: 0.6349
Tuned Model Accuracy: 0.8809523582458496

In [31]:
print("Conclusion")
print("1. The SONAR dataset was successfully preprocessed.")
print("2. An Artificial Neural Network (ANN) model was built.")
print("3. The model was trained and tested successfully.")
print("4. Accuracy, Confusion Matrix and Classification Report were used for evaluation.")
print("5. Hyperparameter tuning was performed by increasing the hidden layers and neurons.")
print("6. The tuned ANN model achieved 88.10% accuracy, which is higher than the default model accuracy of 85.71%. Therefore, the tuned model performed better.")

Conclusion
1. The SONAR dataset was successfully preprocessed.
2. An Artificial Neural Network (ANN) model was built.
3. The model was trained and tested successfully.
4. Accuracy, Confusion Matrix and Classification Report were used for evaluation.
5. Hyperparameter tuning was performed by increasing the hidden layers and neurons.
6. The tuned ANN model achieved 88.10% accuracy, which is higher than the default model accuracy of 85.71%. Therefore, the tuned model performed better.